# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acabado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('medida1', models.FloatField()),
                ('medida2', models.FloatField()),
                ('acabado_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Acabado')),
                ('familia_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Familia')),
                ('material_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Material')),
            ],
        ),
        migrations.CreateModel(
            name='Subtipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('familia_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Familia')),
            ],
        ),
        migrations.CreateModel(
            name='TipoMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='subtipo_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Subtipo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipoMedida_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.TipoMedida'),
        ),
    ]
